# Generated by Django 3.0.8 on 2020-08-05 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0007_auto_20200715_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('payment_value', models.CharField(choices=[(1, 1), (2, 2), (5, 5), (10, 10)], max_length=10)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.Ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
