# Generated by Django 3.0.8 on 2020-08-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_auto_20200805_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_value',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (5, '5'), (10, '10')], max_length=10),
        ),
    ]
