# Generated by Django 3.0.8 on 2020-08-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_auto_20200823_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_value',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (5, '5'), (10, '10')]),
        ),
    ]
