# Generated by Django 3.0.8 on 2020-08-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_auto_20200828_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='charge_id',
            field=models.CharField(default='UNDEFINED', max_length=50),
            preserve_default=False,
        ),
    ]
