# Generated by Django 3.0.8 on 2020-08-28 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_payment_charge_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-date']},
        ),
    ]
